 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 107-301-133
127.0.0.1 - - [08/Aug/2023 22:16:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Aug/2023 22:16:08] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [08/Aug/2023 22:16:08] "[36mGET /static/background.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [08/Aug/2023 22:16:27] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'upload_file' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [08/Aug/2023 22:17:01] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [08/Aug/2023 22:17:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Aug/2023 22:17:27] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [08/Aug/2023 22:17:27] "[36mGET /static/background.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [08/Aug/2023 22:17:48] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'upload_file' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [08/Aug/2023 22:18:01] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [08/Aug/2023 22:19:01] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [08/Aug/2023 22:20:01] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [08/Aug/2023 22:20:10] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'upload_file' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [08/Aug/2023 22:21:01] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [08/Aug/2023 22:21:38] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'upload_file' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [08/Aug/2023 22:22:01] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [08/Aug/2023 22:22:43] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "/home/predictor/Predictor/predictor/lib/python3.10/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'upload_file' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [08/Aug/2023 22:23:01] "HEAD / HTTP/1.1" 200 -
